version: '3.8'
services:
  # The service for your Spring Boot application
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  # The service for your PostgreSQL database
 # db:
  #  image: postgres
   # environment:
    #  POSTGRES_USER: myuser
     # POSTGRES_PASSWORD: password
      #POSTGRES_DB: ecommerce
    #volumes:
     # - postgres-data:/var/lib/postgresql/data
    #ports:
     # - "5432:5432"

#volumes:
 # postgres-data:
